### PR TITLE
(v4.0.0) refactor project structure

### PR DESCRIPTION
**Pull request by cmyui**
went overkill in #145 with switching to new tech and have decided to scrap the progress and redo it in smaller chunks.

once i'm closed to completion i'll turn this post into a nice changelist, so remember to check here again after 4.0.0 release

note that this branch is pretty unstable

### CODE REVIEW

**Comment by cmyui** [comment]
config was changed, if you're a dev and you'd like to play with new changes, here's a sample config (place this at `gulag/.env`) 
```sh
SERVER_ADDR=/tmp/gulag.sock

DB_DSN=mysql://user:passwd@host:port/database
REDIS_DSN=redis://localhost

OSU_API_KEY=

DOMAIN=cmyui.xyz
MIRROR_URL=https://api.chimu.moe/v1

COMMAND_PREFIX=!

SEASONAL_BGS=
MAIN_MENU_ICON=https://akatsuki.pw/static/logos/logo_ingame.png|https://akatsuki.pw

DATADOG_API_KEY=
DATADOG_APP_KEY=

DEBUG=True

PP_CACHED_ACCS=90,95,98,99,100
PP_CACHED_SCORES=800000,850000,900000,950000,1000000

DISALLOWED_NAMES=mrekk,vaxei,btmc,cookiezi
DISALLOWED_PASSWORDS=password,abc123

AUTOMATICALLY_REPORT_PROBLEMS=True

# advanced dev settings

## WARNING: only touch this once you've
##          read through what it enables.
##          you could put your server at risk.
DEVELOPER_MODE=True
```

**Comment by ledlamp** [comment]
wait so what's the redis for?

**Comment by JKBGL** [comment]
> wait so what's the redis for?

caching?

**Comment by ledlamp** [comment]
cant u just like use a variable lol

**Comment by cmyui** [comment]
calculating players ranks easily (bisection algo using zrevrank). the ripple method. perhaps manual bisection algo one day.

**Comment by ledlamp** [comment]
hmm

btw if it's using a db and redis then couldnt u possibly design it as a stateless application that can be scaled with multiple instances? or is that what ur doing

**Comment by cmyui** [comment]
server is getting stable now, probably ready for people to start trying it out.

**Comment by cmyui** [comment]
4.0.0 🥳🥳🥳

**Pull request merged**
