### PR TITLE
gulag systemd service

### PR DESCRIPTION
**Pull request by ledlamp**
you'd want this for a proper installation

### CODE REVIEW

**Comment by m0lese** [comment]
@ledlamp Make it in 1 commit please. And do it via [mysystemd.talos.sh](https://mysystemd.talos.sh).

**Comment by m0lese** [comment]
It has lots of issues, thus the tool to avoid malpractice.

**Comment by ledlamp** [comment]
What are those issues?

**Comment by m0lese** [comment]
Unnecessary comments: [gulag.service#L1](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L1), [gulag.service#L29](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L29), [gulag.service#L12](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L12). Which should be documented somewhere else, e.g: `README.md`

Improper Description: [gulag.service#L4](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L4). More like a service name than an actual description.

Completely unecessary: [gulag.service#L20-L22](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L20-L22)

Malpractice: [gulag.service#L16-L18](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L16-L18). Here how you should be doing:
```bash
WorkingDirectory=/patch/to/gulag
ExecStart=/patch/to/gulag/main.py
```

**Comment by ledlamp** [comment]
> Unnecessary comments: [gulag.service#L1](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L1), [gulag.service#L29](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L29), [gulag.service#L12](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L12). Which should be documented somewhere else, e.g: `README.md`
> 
> Improper Description: [gulag.service#L4](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L4). More like a service name than an actual description.
> 
> Completely unecessary: [gulag.service#L20-L22](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L20-L22)
> 
> Malpractice: [gulag.service#L16-L18](https://github.com/ledlamp/gulag/blob/patch-2/ext/gulag.service#L16-L18). Here how you should be doing:
> 
> ```shell
> WorkingDirectory=/path/to/gulag
> ExecStart=/path/to/gulag/main.py
> ```

Absolutely ridiculous. You're making a fool of yourself.

**Comment by m0lese** [comment]
f0c31164352bc6e1a5a924db7b5020e31866f3e5 lol

**Pull request closed without merging**
