### PR TITLE
Overall project refactoring - focusing around adding more industry-standard tooling

### PR DESCRIPTION
**Pull request by cmyui**
This is a very large (breaking) project refactor, mostly implementing all the new technologies i've come to love at my job, such as FastAPI/Starlette, Pydantic, SQLAlchemy and others.

Planning on this hopefully being a 1-weekend thing!

### CODE REVIEW

**Comment by cmyui** [comment]
config has moved from config.py to environment variables (or a gulag/.env file)

**Comment by ledlamp** [comment]
o shit that's awesome

**Comment by cmyui** [comment]
also probably looking to move subdomain handling to nginx, anyone have any second opinions on this?
```
c.ppy.sh/ -> ppy.sh/cho
a.ppy.sh/ -> ppy.sh/ava
b.ppy.sh/ -> ppy.sh/map
osu.ppy.sh/ -> ppy.sh/osu
```

**Comment by ledlamp** [comment]
what, have ~~nginx~~ the user's reverse proxy rewrite subdomains into the url?

**Comment by cmyui** [comment]
yup

**Comment by ledlamp** [comment]
that would seem really weird externally, please don't do that...

**Comment by ledlamp** [comment]
imo design the program to work with minimal external configuration.

**Comment by cmyui** [comment]
hmm yea true. will think more about where to put the complexity

**Comment by ledlamp** [comment]
o did u consider sqlite?

**Comment by tsunyoku** [comment]
we’re looking more towards postgres because sqlalchemy has awesome tools for it, and postgres overall is really cool. i don’t see gulag using sqlite

**Comment by memsdm05** [comment]
> o did u consider sqlite?

cmyui wants gulag to be the new akatsuki, therefore he's starting to move it into a more "enterprise" direction. Honestly, would be cool to fork gulag and make a version better suited for local enviroments.

**Comment by cmyui** [comment]
> Honestly, would be cool to fork gulag and make a version better suited for local enviroments.

i've been considering making a lightweight osu server (might stream writing it too?)

**Comment by memsdm05** [comment]
@cmyui sqllite, exe, easy setup, config is toml instead of python, flask, built in ssl, automatically exists hosts

honestly that’s a pretty fun go project

**Comment by ledlamp** [comment]
wtf Screenshot_20211208-225108_Chrome

**Comment by cmyui** [comment]
note that the fastapi changes will likely be salvaged in the coming weeks/months, and i'll likely be creating a second osu! server repository for a more barebones osu! server implementation (with more wild/crazy features production servers wouldn't be so interested in).

**Pull request closed without merging**
